---
carwash:

    # Unique identifier for this Nvidia Jetson
    system_id: washngo-lauderhill-lenovo-FL

    # Carwash timezone
    system_timezone: 'America/New_York'

    # Modbus IP address
    modbus_ip: 10.10.10.115

    # Modbus Inversion Mode
    # False: on:1 off:0
    # True:  on:0 off:1
    #

    modbus_signal_pulse_seconds: 2
    modbus_conveyor_plc_delay: 0.5

    modbus_alarm_trigger_inverted: False
    modbus_alarm_trigger_pulse: True
    modbus_alarm_trigger_terminal: 3

    modbus_conveyor_stop_inverted: False
    modbus_conveyor_stop_pulse: False
    modbus_conveyor_stop_terminal: 2

    modbus_conveyor_start_inverted: False
    modbus_conveyor_start_pulse: True
    modbus_conveyor_start_terminal: 4
