connection-string: "DefaultEndpointsProtocol=https;AccountName=nfsandbox6244373916;AccountKey=gUSkGYOQHz+58GrxPuthPbxmUvK+xiQYojcMbgFpD22OXgfCIP2K58E0Ll3thHhqW4TS3HdRenaw+AStPA4Sbg==;EndpointSuffix=core.windows.net"
site-id: "test-Site_1234"
device-id: "test-Device_1234"
change-log-path: "./data/archive/changeLog"
#File Monitoring Settings
monitor-paths: ./data #add space sperated paths here.
ignore-list: "*.idc *.test .data/ignore/* *.sqlite-journal"

#Log File Locations
file-monitor-log: "./data/upload/logs/fileMonitor/fileMonitor.log"
upload-manager-log: "./data/upload/logs/uploadManager/uploadManager.log"
api-log: "./data/upload/logs/api/api.log"
scheduler-log: "./data/upload/logs/scheduler/scheduler.log"
ffmpeg-log: "./data/upload/logs/ffmpeg/ffmpeg.log"
event-log: "./data/upload/events/events.log"
util-log: "./data/upload/logs/util/util.log"
#Setup Options
speed-test : False #This feature works intermitently due to unknown issues with speedtest library.
local-test : True
upload_time: "23:30"
file-persist-days: 14
#Config File Paths
